### ISSUE TITLE
Can’t decrypt Flipnote Studio (dsiware) .cia file

### ISSUE THREAD

**Issue by calvincorrieri** [xxmichibxx/Batch-CIA-3DS-Decryptor-Redux#1]
Is there any chance you could update this to accept dsiware cia files?

If I try running the Flipnote Studio dsiware cia file through the decryptor, it tells me it’s not a 3ds game. Which yeah, it’s technically not, but it’s able to be installed on the 3ds anyway.

I tried running it anyway, but Citra told me to decrypt it first.

Please consider updating this tool to accept dsiware cia files. I would be so freaking happy, and so would a lot of other people trying to emulate this nostalgic gem. I don’t have a 3ds and can’t justify purchasing and modding one just to decrypt a single file. Please consider it, I would be incredibly grateful<3

P.S. I’m not talking about Flipnote Studio 3D, I’m talking about regular old Flipnote Studio

**Comment by xxmichibxx** [comment]
Hey there! DSiware titles, also known as TWL titles, are not supported by the tools used in this script (decrypt.exe). Although, I tried Flipnote Studio CIA files from three different sources. They were all decrypted (NoCrypto). However, I was able to installing them with Citra or Lime3DS, the app doesn't show up on the installed titles list. Manually booting the .APP file isn't supported.

AFAIK, TWL titles are indeed not supported in Citra/Lime3DS. I recommend using MelonDS, which fully supports DSiware.
